{
 "title": "MissionControl",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fuid", "label": "Flight ID", "query": ".*" }
  ]
 },
 "panels": [
  { "title": "Vessel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mass",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vessel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mass\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Thrust",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "forceN" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vessel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"thrust\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Thrust Weight Ratio (TWR)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vessel\")\n  |> filter(fn: (r) => r[\"_field\"] == \"thrust_weight_ratio\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Flight", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mean_altitude\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_air_temperature\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Pitch / Heading / Roll",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pitch\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"heading\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"roll\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"surface_spped\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"flight\")\n  |> filter(fn: (r) => r[\"_field\"] == \"orbital_spped\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Orbit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orbit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"apoapsis_altitude\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"orbit\")\n  |> filter(fn: (r) => r[\"_field\"] == \"periapsis_altitude\")\n  |> filter(fn: (r) => r[\"uid\"] =~ /${fuid}/)\n  |> group(columns: [\"uid\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}